# Generated by Django 4.2.30 on 2026-09-06 18:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='المالك الرئيسي')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الدور')),
                ('is_system', models.BooleanField(default=False, help_text='الأدوار الأساسية (مدير/كاشير/مشاهد) تُنشأ تلقائياً، ويمكن تعديل صلاحياتها لكن لا يمكن حذفها', verbose_name='دور أساسي')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='إدارة الموظفين والأدوار')),
                ('can_delete_records', models.BooleanField(default=False, verbose_name='حذف السجلات (فواتير/أصناف/زبائن/موردون)')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='عرض التقارير المالية')),
                ('can_add_customer', models.BooleanField(default=True, verbose_name='إضافة زبائن')),
                ('can_edit_customer', models.BooleanField(default=True, verbose_name='تعديل بيانات الزبائن')),
                ('can_delete_customer', models.BooleanField(default=False, verbose_name='حذف زبائن')),
                ('can_view_all_customers', models.BooleanField(default=True, verbose_name='عرض جميع الزبائن')),
                ('can_add_product', models.BooleanField(default=True, verbose_name='إضافة أصناف')),
                ('can_edit_product', models.BooleanField(default=True, verbose_name='تعديل الأصناف')),
                ('can_delete_product', models.BooleanField(default=False, verbose_name='حذف أصناف')),
                ('can_manage_purchases', models.BooleanField(default=False, verbose_name='إدارة المشتريات والموردين')),
                ('can_add_sale', models.BooleanField(default=True, verbose_name='إنشاء فواتير بيع')),
                ('can_delete_sale', models.BooleanField(default=False, verbose_name='حذف فواتير')),
                ('can_add_expense', models.BooleanField(default=False, verbose_name='إضافة مصروفات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to=settings.AUTH_USER_MODEL, verbose_name='صاحب العمل')),
            ],
            options={
                'verbose_name': 'دور وظيفي',
                'verbose_name_plural': 'الأدوار الوظيفية',
                'ordering': ['-is_system', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text='فارغ لصاحب الحساب الرئيسي فقط', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role', verbose_name='الدور الوظيفي'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
