# Generated by Django 4.2.30 on 2026-09-06 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الزبون')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name='اسم النشاط')),
                ('activity_type', models.CharField(choices=[('retail', 'قطاعي'), ('wholesale', 'جملة'), ('both', 'جملة وقطاعي')], default='retail', max_length=20, verbose_name='نوع النشاط')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('personal_phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف الشخصي')),
                ('business_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف النشاط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'زبون',
                'verbose_name_plural': 'الزبائن',
                'ordering': ['name'],
            },
        ),
    ]
